[package]
name = "elegant-clipboard-gpui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clipboard-core = { path = "../clipboard-core" }

[target.'cfg(windows)'.dependencies]
async-channel.workspace = true
clipboard-platform = { path = "../clipboard-platform" }
chrono.workspace = true
gpui-kit.workspace = true
directories.workspace = true
raw-window-handle.workspace = true
serde_json.workspace = true
tray-icon.workspace = true
windows = { workspace = true, features = ["Win32_Foundation", "Win32_Graphics_Gdi", "Win32_Media_Audio", "Win32_System_DataExchange", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }

[dev-dependencies]
tempfile.workspace = true
