[package]
name = "clipboard-platform"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-channel.workspace = true
clipboard-core = { path = "../clipboard-core" }

[target.'cfg(windows)'.dependencies]
clipboard-rs.workspace = true
directories.workspace = true
windows.workspace = true

[dev-dependencies]
tempfile.workspace = true
